services:
  app:
    build:
      dockerfile: Dockerfile
      context: backend
    command: "python -m application.run_main"
    environment:
      PYTHONPATH: app
      DB_NAME: dyadya_shop
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
    ports:
      - "8000:8000"
    depends_on:
      pg:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: ./poetry.lock     

  taskiq_redis_worker:
    build: backend
    command: taskiq worker infra.redis.taskiq_redis:redis_broker
    depends_on:
      - redis
    enviroment:
      PYTHONPATH: app  

  taskiq_rabbitmq_worker:
    build: backend
    command: taskiq worker infra.broker.taskiq_rabbitmq:rabbitmq_broker
    depends_on:
      - rabbitmq

  taskiq_redis_scheduler:
    build: backend
    command: taskiq scheduler infra.redis.taskiq_redis:redis_broker:scheduler
    depends_on:
      - redis

  taskiq_rabbitmq_scheduler:
    build: backend
    command: taskiq scheduler infra.broker.taskiq_rabbitmq:scheduler
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --appendfsync everysec
    volumes:
      - redis_data:/data

  pg:
    image: postgres:17
    environment:
      POSTGRES_DB: dyadya_shop
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 3s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: dyadya@test.org
      PGADMIN_DEFAULT_PASSWORD: dyadya_123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      pg:
        condition: service_healthy


volumes:
  pgdata:
  rabbitmq-data:
  redis_data: